apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "iso-dv"
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
      registry:
        url: 'docker://quay.io/openshift-cnv/containerdisks:Win10_21H2_English_x64'
        pullMethod: node
  storage:
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "7Gi"
